language: android
sudo: false

android:
  components:
  - android-27
  - tools
  - com.android.tools.build:gradle:3.3.1

  licenses:
  - android-sdk-license-.+

script:
  - ./gradlew :app:assembleRelease